// src/app/api/register/route.ts
import { hash } from 'bcryptjs';
import { query as pgQuery } from '../../../lib/db'; // Correct relative path to your db.ts

export async function POST(req: Request) {
  try {
    const { email, password } = await req.json();

    if (!email || !password) {
      return new Response(JSON.stringify({ message: 'Email and password are required.' }), { status: 400 });
    }

    // --- PostgreSQL specific logic ---

    // 1. Check if user already exists
    const existingUserResult = await pgQuery<{ email: string }>(
      'SELECT email FROM users WHERE email = $1',
      [email]
    );

    if (existingUserResult.rows.length > 0) {
      return new Response(JSON.stringify({ message: 'User with this email already exists.' }), { status: 409 });
    }

    // 2. Hash the password
    const hashedPassword = await hash(password, 12); // Use a salt round of 12 or higher

    // 3. Insert the new user into the database
    // IMPORTANT: Make sure your 'users' table has 'email' and 'password_hash' columns
    // And 'id' if you want to return it, often generated by SERIAL or UUID type.
    const insertUserResult = await pgQuery<{ id: string; email: string }>(
      'INSERT INTO users (email, password_hash) VALUES ($1, $2) RETURNING id, email',
      [email, hashedPassword]
    );

    const newUser = insertUserResult.rows[0];

    return new Response(
      JSON.stringify({ message: 'User registered successfully!', user: { id: newUser.id, email: newUser.email } }),
      { status: 201 }
    );

  } catch (error) {
    console.error('Registration error:', error);
    return new Response(JSON.stringify({ message: 'Internal server error during registration.' }), { status: 500 });
  }
}